### ISSUE TITLE
Alpine non root user

### ISSUE THREAD

**Issue by richardjharding** [Azure/azure-functions-docker#118]
I'm using the Alpine dotnet images and our vulnerability checking tool (Twistlock) is picking up a few out of date packages which I think I can fix but one issue is its suggesting that the image should be created with a non root user 
Is any work underway to support this?
I'm able to get an asp.net core app on say ```mcr.microsoft.com/dotnet/core/runtime-deps:2.2.4-alpine3.9 ``` to run as non root but when I try with the functions runtime I get a number of permission errors  such as
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Permission denied) ---> System.Net.Sockets.SocketException: Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
```

this is after setting permissions for the new user on the following
```
/azure-functions-host
/FuncExtensionBundles
```

any ideas what I'm missing?

**Comment by richardjharding** [comment]
Ok so this looks like an issue trying to bind to a port less than 1024 and is expected
The only way I could see to specify an alternative port for the host to listen on was to set the following env var
```ENV ASPNETCORE_URLS='http://+:5000'```
Is there an alternative settings file that would also work?

**Comment by owenneil** [comment]
I tried the same thing, I was able to get a little further. I added this:
RUN apk add --no-cache libcap

and 

RUN setcap 'cap_net_bind_service=+ep' /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost

Unfortunately, now I get "Unhandled Exception: System.InvalidOperationException: Host.DestinationHostUrl must be specified either as an environment variable or as a command-line switch." I'm not quite sure why.

**Comment by gabscogna** [comment]
Same here. Checkmarx doesn't let us use root users in Docker files.
I tried to use `WEBSITES_PORT=8080` like documentation says, but it didn't work too.

**Comment by gabscogna** [comment]
`WEBSITES_PORT` and `ASPNETCORE_URLS` doesn't work with Azure Function containers (not for me at least).

But `PORT` does. `ENV PORT=8080`:

```plaintext
2025-06-18 10:14:49 Hosting environment: Production
2025-06-18 10:14:49 Content root path: /azure-functions-host
2025-06-18 10:14:49 Now listening on: http://[::]:8080
2025-06-18 10:14:49 Application started. Press Ctrl+C to shut down.
```

**Comment by vivekjilla** [comment]
For binding a non-root port, the working configuration reported in this thread is `ENV PORT=8080`. Dedicated Alpine image variants aren't a supported option. We're closing this; if you still see non-root binding issues on a current supported Linux image, please open a new issue with the tag/digest and a repro.
