### ISSUE TITLE
Unhandled async expection not logged during startup

### ISSUE THREAD

**Issue by Rickaro** [Azure/azure-functions-docker#218]
### Envirounment

OS:**Linux**
Language: **Javascript**
Azure Function Core Tools: **2.7.2100**
Function Runtime Version: **2.0.12961.0**
Base docker image:
mcr.microsoft.com/azure-functions/node             **2.0                 1460b85a9170**

Issue: if function code throws async exception, that was not handled, container terminates, without any log information about error.

### How to reproduce
```
agent@agent:~$ func init --docker --worker-runtime node
agent@agent:~$ func new --template HttpTrigger --name fail-func

agent@agent:~$ echo "setTimeout(() => { throw new Error(); }, 1000);" > fail-func/index.js

agent@agent:~$ func start
```
Test it locally
```
agent@agent:~$ func start
```
Error is present in logs (I've slightly format long string)
```
[2/20/20 7:20:00 AM] [error] Worker 11206066-c65d-4743-ac8b-3f0252940e76 uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): 
Error
     at Timeout.setTimeout [as _onTimeout] (/opt/agent-home/fail-func/index.js:1:26)
     at ontimeout (timers.js:436:11)
     at tryOnTimeout (timers.js:300:5)
     at listOnTimeout (timers.js:263:5)
     at Timer.processTimers (timers.js:223:10)
[2/20/20 7:20:00 AM] Worker 11206066-c65d-4743-ac8b-3f0252940e76 exited with code 1
```
Now, let's create container and run it
```
agent@agent:~$ docker build .
Successfully built 16b77c62c1e9

agent@agent:~$ docker run 16b77c62c1e9
```

As a result, we will get **fail**, that worker restart retry count is reached, but no information about worker errors
```
info: Host.Startup[0]
      Job host started
Hosting environment: Production
Content root path: /
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
fail: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
      Exceeded language worker restart retry count for runtime:node. Shutting down Functions Host
```

### Expected behavior
Exception should be present in log file, like when function started locally

May be it could be logged with some env variable set, but I did not find any that could help me

**Comment by vivekjilla** [comment]
This describes host/worker logging behavior rather than an image issue, and it was reported on a long-retired image with no repro since February 20, 2020 (about 6 years). We're closing it here. If it reproduces on a current supported Node image, please open a new issue; host logging behavior is tracked in the azure-functions-host repo.
