### ISSUE TITLE
Docker images still reference .NET 6 preview 7

### ISSUE THREAD

**Issue by cheesi** [Azure/azure-functions-docker#505]
I'm currently facing an issue with the dotnet isolated images, as my images are build with `mcr.microsoft.com/dotnet/sdk:6.0`, which already points to .NET 6 RC 1.

I get the following error:
```
root@6e72bc643f84:~/site/wwwroot# dotnet My.FunctionApp.dll 
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0-rc.1.21451.13' was not found.
  - The following frameworks were found:
      6.0.0-preview.7.21377.19 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0-rc.1.21451.13&arch=x64&rid=debian.11-x64
```

The original issue was something else. I only discovered this, after I tried to manually start the function dll within the container:
```
azfunc_ti    | info: Host.Startup[413]
azfunc_ti    |       Host started (1188ms)
azfunc_ti    | info: Host.Startup[0]
azfunc_ti    |       Job host started
azfunc_ti    | Hosting environment: Production
azfunc_ti    | Content root path: /
azfunc_ti    | Now listening on: http://[::]:80
azfunc_ti    | Application started. Press Ctrl+C to shut down.
azfunc_ti    | info: Function.MyAzureFunction[1]
azfunc_ti    |       Executing 'Functions.MyAzureFunction' (Reason='(null)', Id=RANDOMGUID)
azfunc_ti    | info: Function.MyAzureFunction[0]
azfunc_ti    |       Trigger Details: PartionId: 0, Offset: 3200-4400, EnqueueTimeUtc: 2021-09-16T14:36:46.5870000+00:00-2021-09-16T14:46:02.8120000+00:00, SequenceNumber: 8-11, Count: 4
azfunc_ti    | info: Host.General[337]
azfunc_ti    |       Host lock lease acquired by instance ID '000000000000000000000000D97B0BFA'.
azfunc_ti    | fail: Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker[0]
azfunc_ti    |       Final functionDispatcher state: WorkerProcessRestarting. Initialization timed out and host is shutting down
azfunc_ti    | info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
azfunc_ti    |       Stopping JobHost
azfunc_ti    | info: Host.Startup[0]
azfunc_ti    |       Stopping the listener 'Microsoft.Azure.WebJobs.EventHubs.EventHubListener' for function 'MyAzureFunction'
azfunc_ti    | fail: Function.MyAzureFunction[3]
azfunc_ti    |       Executed 'Functions.MyAzureFunction' (Failed, Id=c6631745-dde2-4920-b729-d449dbbfde80, Duration=44935ms)
azfunc_ti    |       Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.MyAzureFunction
azfunc_ti    |        ---> System.InvalidOperationException: Did not find any initialized language workers
azfunc_ti    |          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel(IEnumerable`1 rpcWorkerChannels, Int32 maxProcessCount) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcherLoadBalancer.cs:line 27
azfunc_ti    |          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InvokeAsync(ScriptInvocationContext invocationContext) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 308
azfunc_ti    |          at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 95
azfunc_ti    |          at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 572
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 518
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 296
azfunc_ti    |          --- End of inner exception stack trace ---
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 343
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 105
azfunc_ti    | fail: Host.Results[0]
azfunc_ti    |       Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.MyAzureFunction
azfunc_ti    |        ---> System.InvalidOperationException: Did not find any initialized language workers
azfunc_ti    |          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel(IEnumerable`1 rpcWorkerChannels, Int32 maxProcessCount) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcherLoadBalancer.cs:line 27
azfunc_ti    |          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InvokeAsync(ScriptInvocationContext invocationContext) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 308
azfunc_ti    |          at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 95
azfunc_ti    |          at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 572
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 518
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 296
azfunc_ti    |          --- End of inner exception stack trace ---
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 343
azfunc_ti    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 105
azfunc_ti    | info: Host.Startup[0]
azfunc_ti    |       Stopped the listener 'Microsoft.Azure.WebJobs.EventHubs.EventHubListener' for function 'MyAzureFunction'
azfunc_ti    | info: Host.Startup[0]
azfunc_ti    |       Job host stopped
azfunc_ti exited with code 0
```

I already prepared a pull request to update all the docker images: https://github.com/Azure/azure-functions-docker/pull/504

**Comment by cheesi** [comment]
Already handled by https://github.com/Azure/azure-functions-docker/commit/17e18c11ae6c346541fa2c18c752d7be73bdb89e.
