### ISSUE TITLE
Error Indexing Methods in Latest Image

### ISSUE THREAD

**Issue by wsugarman** [Azure/azure-functions-docker#648]
Hi --

As of the latest dotnet image, `mcr.microsoft.com/azure-functions/dotnet:4-slim@sha256:7336219bb35a9f01642261fe238f4260ed30087c50123cc1397823d5617d7060`, the job host can no longer index many of my Azure Functions on start-up. I am running a docker-compose project in Visual Studio and now I see log entries like:

```
info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
      Starting JobHost
fail: Host.Startup[0]
      Error indexing method '<function1>'
      Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method '<function1>'
       ---> System.InvalidOperationException: Method overloads are not supported. There are multiple methods with the name '<Method1>'.
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndex.Add(IFunctionDefinition function, FunctionDescriptor descriptor, MethodInfo method) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndex.cs:line 30
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 349
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 149
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 157
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 85
```

Upon closer inspection, my Timer trigger does not appear impacted, but all of my Durable Function triggers (i.e. orchestrations and activities) cannot index. I reverted the image back to `mcr.microsoft.com/azure-functions/dotnet:4-slim@sha256:8adc35bc166c711e0cb945aecce2776c7884f7c7a903b16b219b6b2df6aadce9` and it ran without issue.

**Comment by tomvo12** [comment]
Same problem for me, as long as I pin the docker image version to 4.1.3, my functions come up without error. If I use 4.2.1 I get the following:
```
fail: Host.Startup[0]
      Error indexing method 'LiveFunction'
      Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'LiveFunction'
       ---> System.InvalidOperationException: Method overloads are not supported. There are multiple methods with the name 'DevPortal.Provisioning.Functions.HealthFunction.RunLive'.
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndex.Add(IFunctionDefinition function, FunctionDescriptor descriptor, MethodInfo method) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndex.cs:line 30
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 349
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 149
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 157
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 85
```

**Comment by balag0** [comment]
Thanks for reporting. We are investigating actively. Please use the previous image in the meantime. Also the issue seems to be specific to functions V4. Just wanted to check if anyone is seeing this in earlier functions versions as well?

**Comment by surgupta-msft** [comment]
@wsugarman and @tomvo12 I am working on investigating this issue. Can you please share more details about your apps (name, configuration, app service plan tier) which showed these exceptions?

**Comment by wsugarman** [comment]
We use these docker images when deploying our functions to Azure Kubernetes Service, so unfortunately I don't have an app with details to share. However, our docker-compose project we include in our solution can consistently reproduce the issue here if the base image is updated for functions: https://github.com/microsoft/dicom-server/blob/main/Microsoft.Health.Dicom.sln

**Comment by wsugarman** [comment]
@surgupta-msft - Is there any update on this issue?

**Comment by wsugarman** [comment]
I see that the issue appears to be fixed in `mcr.microsoft.com/azure-functions/dotnet:4.3.0-slim`! Thank you!

But I see that the `4-slim` tag has not been updated. Are the various `4*` tags meant to match the latest `4.x.y*` tags, or are they on a different release cadence?

```bash
$ docker images --digests
REPOSITORY                                 TAG          DIGEST                                                                    IMAGE ID       CREATED       SIZE
mcr.microsoft.com/azure-functions/dotnet   4.3.0-slim   sha256:bca8c93111e342170a1520e8bb162731f9149cb5adebffa017c67664626d9499   9de6f331c705   2 weeks ago   778MB
mcr.microsoft.com/azure-functions/dotnet   4-slim       sha256:8adc35bc166c711e0cb945aecce2776c7884f7c7a903b16b219b6b2df6aadce9   b28ba2b489a0   6 weeks ago   800MB
```

**Comment by surgupta-msft** [comment]
Tagging @pragnagopa

**Comment by pragnagopa** [comment]
@VpOfEngineering can you please provide update on the release? cc @CooperLink

**Comment by VpOfEngineering** [comment]
This is fixed in version `4.3.x` which we are in the process of rolling out. 😊

**Comment by pragnagopa** [comment]
@VpOfEngineering / @CooperLink - did we miss rolling back `4-slim` to prev host version?

**Comment by wsugarman** [comment]
Closing as this appears to be fixed
