### ISSUE TITLE
.NET 6: Runtime Config Switch "System.Drawing.EnableUnixSupport" Not Supported?

### ISSUE THREAD

**Issue by devax** [Azure/azure-functions-docker#698]
Hi all,
We're trying to upgrade a containerized Azure Function from .NET Core 3.1 / Runtime 3 to .NET 6 / Runtime 4, in process. We would like to activate the `System.Drawing.EnableUnixSupport` for backward compatibility reasons, as described here: https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only
Unfortunately, the switch gets not recognized by the runtime and the code fails with this exception:
```console
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.  
---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
    at System.Drawing.LibraryResolver.EnsureRegistered()
    at System.Drawing.SafeNativeMethods.Gdip..cctor()
    --- End of inner exception stack trace --- 
```

These are the main parts of our Dockerfile:
```dockerfile
FROM mcr.microsoft.com/azure-functions/dotnet:4.5.1
RUN  sed -i "s/main/main contrib/g" /etc/apt/sources.list \
  && echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections \
  && apt-get update \
  && apt-get install -y --allow-unauthenticated --no-install-recommends \
    libc6-dev \
    libgdiplus \
    libx11-dev \
    fontconfig \
    ttf-mscorefonts-installer \
    tzdata \
  && rm -rf /var/lib/apt/lists/* \
  && fc-cache -f -v \
  && sed -i '/^ssl_conf = ssl_sect$/s/^/#/' /etc/ssl/openssl.cnf \
  && update-ca-certificates

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    FUNCTIONS_WORKER_RUNTIME="dotnet" \
    TZ="Europe/Berlin" \
    DOTNET_System_Drawing_EnableUnixSupport=true \
    DOTNET_SYSTEM_DRAWING_ENABLEUNIXSUPPORT=true

COPY --from=builder "/publish" "/home/site/wwwroot"
WORKDIR /home/site/wwwroot
```

We have also tried to add the configuration directly to the file `/azure-functions-host/runtimeconfig.template.json`:
```json
{
    "configProperties": {
        // Protect users from https://github.com/dotnet/runtime/pull/59716.
        // Can be removed after running on .NET 6.0 GA
        "Microsoft.Extensions.Configuration.BindSingleElementsToArray": false,
        // Fix for https://github.com/dotnet/runtime/issues/56052
        "System.Diagnostics.Tracing.EventSource.AllowDuplicateSourceNames": true,
        
        // Manually added config here:
        "System.Drawing.EnableUnixSupport": true
    }
}
```
But still getting the same exception.

Is there a way we can make the runtime respect the switch? Any help would be much appreciated. Thank you!

**Comment by devax** [comment]
Looks like we found a way to activate the switch in an in-process functions app, by activating the switch programmatically in Startup, like so:

```csharp
public class Startup : FunctionsStartup
{
    // ...
    public override void Configure(IFunctionsHostBuilder builder)
    {
        AppContext.SetSwitch("System.Drawing.EnableUnixSupport", true);
        // ...
    }
}
```

This is somewhat documented here: https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.setswitch?view=net-6.0

Not sure if this is the best way of doing this in a functions project, but for now that's the only workaround we've found.
