### ISSUE TITLE
func azure functionapp publish --build-native-deps fails with docker error

### ISSUE THREAD

**Issue by sandorbihary** [Azure/azure-functions-docker#78]
Hi All!
I am tryting to publish a python function but I got an error message.
I used this command: 
` func azure functionapp publish sanyifunction  --build-native-deps`

Environment is Centos7 and Python 3.6.7

This is the error message:

```
Getting site publishing info...
Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0.12285'..done
Running 'docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0.12285'..done
Running 'docker exec -t 088384 mkdir -p /home/site/wwwroot/'..done
Running 'docker cp /tmp/15pjtmni.l2t/. 088384:/home/site/wwwroot'..done
Running 'docker kill 088384'..done

Error running docker cp /tmp/15pjtmni.l2t/. 08838429b9ba5e734c977c03f3008ff86b6616f7f66c68063d3bafd3fc63a6dc:/home/site/wwwroot.
output:
Error: No such container:path: 08838429b9ba5e734c977c03f3008ff86b6616f7f66c68063d3bafd3fc63a6dc:/home/site
```

This is the requirements.txt

```
cat requirements.txt
azure-functions==1.0.0b3
azure-functions-worker==1.0.0b3
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.12.0
azure
azure-mgmt-resource
azure-datalake-store
azure-mgmt-datalake-store
azure-mgmt-datalake-analytics
```

The code is running locally. Also I have to use the --build-native-deps otherwise I get this error message:

`There was an error restoring dependencies.ERROR: cannot install cryptography-2.5 dependency: binary dependencies without wheels are not supported.  Use the --build-native-deps option to automatically build and configure the dependencies using a Docker container. More information at https://aka.ms/func-python-publish`

Can it be a bug? Or maybe I am doing something wrong?

**Comment by ahmelsayed** [comment]
It seems to be an issue with dotnet in docker on CentOS specifically https://github.com/dotnet/dotnet-docker/issues/644 https://github.com/dotnet/dotnet-docker/issues/485. I haven't found any explanation as to why that's happening, but setting a `WORKDIR` in the docker file seems to be the fix..!! I guess will do that :)

**Comment by sandorbihary** [comment]
Sure, sounds good:) Will you update the container? So I only need to re-pull it?

**Comment by trijimonpr** [comment]
@ahmelsayed I am still seeing this issue when I try to publish a function app using --build-native-apps option. I am using func binary of version 2.6.666 in centos 7.2.1511. Is there a workaround or a way to deploy from centos? Thanks!

**Command:**
`CLI_DEBUG=1  func azure functionapp publish python-sample-app --build-native-deps`

**Log:**
`Azure.Functions.Cli.Common.CliException: Error running docker exec -t 70156db3faef95b81dd6635867939e496bc26003d610dd59b555563c6162e5ee chmod +x /python_docker_build.sh.
output: 

Error response from daemon: Container 70156db3faef95b81dd6635867939e496bc26003d610dd59b555563c6162e5ee is not running


   at Azure.Functions.Cli.Helpers.RetryHelper.Retry(Func`1 func, Int32 retryCount, TimeSpan retryDelay, Boolean displayError) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\RetryHelper.cs:line 29
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishZipDeploy(Site functionApp, Func`1 zipFileFactory) in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 392
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 305
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 166
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in C:\azure-functions-cli\src\Azure.Functions.Cli\ConsoleApp.cs:line 54
`

**Comment by vivekjilla** [comment]
The thread traced this to a CentOS-specific dotnet-in-docker problem, with a WORKDIR workaround discussed; the referenced image and command are long out of date. With no activity since April 24, 2019 (about 7 years), we're closing this. If the problem reproduces with current tooling on a current supported image, please open a new issue.
