### ISSUE TITLE
Failed to start a new language worker for runtime: node

### ISSUE THREAD

**Issue by kaminirio** [Azure/azure-functions-docker#907]
Today my docker image has stopped working with the error below, I have tried to run an empty docker file with simple nodejs app, but the same issue. 
```fail: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
      Failed to start a new language worker for runtime: node.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 283
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, IEnumerable`1 languages) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 152
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, String language) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 144
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(IEnumerable`1 languages) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 135
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.<>c__DisplayClass55_0.<<StartWorkerProcesses>b__0>d.MoveNext() in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 215
```

docker file is simple

```
FROM mcr.microsoft.com/azure-functions/node:4-node18
ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true
COPY . /home/site/wwwroot/
```
I have tried different images, but issue it the same
Any idea what the issue might be?

**Comment by vijaykumar911** [comment]
Hi @kaminirio will update you soon.

**Comment by vijaykumar911** [comment]
check that your Docker container has proper networking configuration to communicate with the required dependencies and resources. Make sure it can access the necessary Azure services and endpoint.   if you have made any recent changes to your local development environment, such as updates to Docker, Node.js, or other related tools. Incompatibilities or misconfigurations in the local environment can sometimes cause runtime issues.
Review the logs generated by the Docker container to gather more information about the issue. You can try running the container with increased verbosity to get more detailed error messages. Additionally, check if any other error messages or warnings are displayed in the logs.
 Instead of using the mcr.microsoft.com/azure-functions/node:4-node18 base image, try using a different version or a different base image altogether. This change can help identify if the issue is specific to the runtime image you are using.

**Comment by kaminirio** [comment]
@vijaykumar911 Hi, I have tried different setups, laptops, projects and etc. I created simple nodejs project and expecting to get homepage ("Your Functions 4.0 app is up and running),  see the example here https://azureossd.github.io/2023/03/20/how-to-deploy-azure-functions-as-custom-container-using-azure-devops/

There is the test project
https://github.com/kaminirio/func-node-docker

**Comment by kaminirio** [comment]
The issue was in docker on M1. By some reason, after restart the docker app is disabled support of Rosetta. After enabling back Rosseta, it returned to work
